# Lie Leon Alexius
name: Simulator Test

# control the action to triggers on all push, pull request to main branch
on: 
  push:
    branches:
      - 'main'
      - 'Leon/*'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make Test 1
      run: make
    - name: Make Test 2
      run: make clean
    - name: Run Samples
      run: bash src/assets/scripts/build_test.sh
    
  edge-case-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Run Edge Case Tests
      run: |
        make release
        bash src/assets/scripts/edge_case_test.sh
        make clean
