name: C/C++ CI

# control the action to triggers on all push, pull request to main branch
on: 
  push:
    branches:
      - 'main'
      - 'Leon/*'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Setup environment
    #   run: bash src/assets/scripts/setup.sh
    - name: Make Test 1
      run: make
    - name: Run Samples
      run: |
        echo "IJK Standard"
        ./cache -c 2147483646 --cacheline-size 16 --l1-lines 4 --l2-lines 16 --pretty-print true examples/ijk.csv
        echo "=================================================================================="
        
        echo "IJK Optimized 1"
        ./cache -c 2147483646 --cacheline-size 16 --l1-lines 4 --l2-lines 16 --pretty-print true examples/ijk_opt1.csv
        echo "=================================================================================="

        echo "IJK Optimized 2"
        ./cache -c 2147483646 --cacheline-size 16 --l1-lines 4 --l2-lines 16 --pretty-print true examples/ijk_opt2.csv
        echo "=================================================================================="
    - name: Make Test 2
      run: make clean
    
  edge-case-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Run Edge Case Tests
      run: |
        make
        bash src/assets/scripts/edge_case_test.sh
